services:
  - type: web
    name: karma-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend.app:app --workers=4 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_URL
        sync: false  # Esto significa que deberás configurar esta variable manualmente en el dashboard de Render
      - key: SUPABASE_KEY
        sync: false  # Esto significa que deberás configurar esta variable manualmente en el dashboard de Render
    healthCheckPath: /
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3